#!/usr/bin/env node
import { mkdirSync, readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { dirname, extname, join, normalize, relative, resolve } from 'node:path';

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), '..');
const SRC = join(ROOT, 'src');
const OUT_DIR = join(ROOT, 'reports', 'debt');

function walk(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    const stat = statSync(path);
    if (stat.isDirectory()) {
      if (name === 'node_modules' || name === 'dist') continue;
      walk(path, acc);
    } else if (path.endsWith('.ts')) {
      acc.push(path);
    }
  }
  return acc;
}

const files = walk(SRC);
const sourceFiles = files.filter((file) => !file.includes('/__tests__/'));
const testFiles = files.filter((file) => file.includes('/__tests__/'));
const fileText = new Map(files.map((file) => [file, readFileSync(file, 'utf-8')]));
const TEST_ONLY_IMPORT_ALLOWLIST = new Set(['src/main.ts']);

function rel(path) {
  return relative(ROOT, path);
}

function countPattern(pattern, candidates = sourceFiles) {
  const hits = [];
  for (const file of candidates) {
    const text = fileText.get(file) ?? '';
    const count = [...text.matchAll(pattern)].length;
    if (count > 0) hits.push({ file: rel(file), count });
  }
  return hits;
}

function mdTable(headers, rows) {
  if (!rows.length) return '_None._\n';
  return [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map((cell) => String(cell).replace(/\n/g, '<br>')).join(' | ')} |`),
    '',
  ].join('\n');
}

function writeReport(name, content) {
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, name), `${content.trimEnd()}\n`);
}

function canonicalKinds() {
  const schemaPath = join(SRC, 'canonical', 'schema.ts');
  const text = readFileSync(schemaPath, 'utf-8');
  return [...text.matchAll(/kind:\s*z\.literal\('([^']+)'\)/g)]
    .map((match) => match[1])
    .filter((kind, index, all) => all.indexOf(kind) === index);
}

const CANONICAL_EFFECT_PATTERNS = {
  text_delta: /onTextDelta\s*:/g,
  thinking_delta: /onThinkingDelta\s*:/g,
  tool_start: /onToolStart\s*:/g,
  tool_result: /onToolResult\s*:/g,
  tool_progress: /onToolProgress\s*:/g,
  agent_start: /onAgentStart\s*:/g,
  agent_progress: /onAgentProgress\s*:/g,
  agent_complete: /onAgentComplete\s*:/g,
  query_result: /onQueryResult\s*:/g,
  error: /onError\s*:/g,
  status: /onStatus\s*:/g,
  session_info: /onSessionInfo\s*:/g,
  tool_use_summary: /onToolUseSummary\s*:/g,
  api_retry: /onApiRetry\s*:/g,
  compact_boundary: /onCompactBoundary\s*:/g,
  prompt_suggestion: /onPromptSuggestion\s*:/g,
  rate_limit: /onRateLimit\s*:/g,
  todo_update: /onTodoUpdate\s*:/g,
};

function auditCanonical() {
  const rows = [];
  for (const kind of canonicalKinds()) {
    const quotedKind = kind.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const producers = countPattern(
      new RegExp(`kind:\\s*['"]${quotedKind}['"]`, 'g'),
      sourceFiles.filter((file) => !file.endsWith('/canonical/schema.ts')),
    );
    const switchConsumers = countPattern(
      new RegExp(`case\\s+['"]${quotedKind}['"]`, 'g'),
      sourceFiles.filter((file) => !file.endsWith('/canonical/schema.ts')),
    );
    const nonConversationConsumers = switchConsumers.filter(
      (hit) => hit.file !== 'src/utils/conversation.ts',
    );
    const testHits = countPattern(
      new RegExp(`['"]${quotedKind}['"]`, 'g'),
      testFiles,
    );
    const effectPattern = CANONICAL_EFFECT_PATTERNS[kind];
    const effectConsumers = effectPattern ? countPattern(effectPattern, sourceFiles) : [];

    const notes = [];
    if (producers.length === 0) notes.push('no producer');
    if (switchConsumers.length === 0) notes.push('no switch consumer');
    if (
      switchConsumers.length === 1 &&
      switchConsumers[0].file === 'src/utils/conversation.ts' &&
      effectConsumers.length === 0
    ) {
      notes.push('only dispatched by ConversationEngine');
    }
    if (
      nonConversationConsumers.length === 0 &&
      effectConsumers.length === 0 &&
      testHits.length > 0
    ) {
      notes.push('possibly tests-only after dispatch');
    }

    rows.push([
      kind,
      producers.map((h) => `${h.file} (${h.count})`).join('<br>') || '-',
      switchConsumers.map((h) => `${h.file} (${h.count})`).join('<br>') || '-',
      effectConsumers.map((h) => `${h.file} (${h.count})`).join('<br>') || '-',
      testHits.length ? `${testHits.length} files` : '-',
      notes.join('; ') || '-',
    ]);
  }

  writeReport(
    'canonical-events.md',
    `# Canonical Event Audit

Generated by \`npm run audit:debt\`.

Heuristic: a healthy canonical event should have at least one provider/runtime producer and a real consumer beyond tests. Most events are consumed by ConversationEngine first and then by an onX callback; the Effect consumers column tracks that second hop.

${mdTable(['Event', 'Producers', 'Switch consumers', 'Effect consumers', 'Test refs', 'Notes'], rows)}`,
  );

  return rows.filter((row) => row[5] !== '-').length;
}

function formattableTypes() {
  const path = join(SRC, 'formatting', 'message-types.ts');
  const text = readFileSync(path, 'utf-8');
  return [...text.matchAll(/\|\s*\{\s*type:\s*'([^']+)'/g)].map((match) => match[1]);
}

function auditFormattableMessages() {
  const rows = [];
  for (const type of formattableTypes()) {
    const escaped = type.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const producers = countPattern(
      new RegExp(`type:\\s*['"]${escaped}['"]`, 'g'),
      sourceFiles.filter((file) => !file.endsWith('/formatting/message-types.ts')),
    );
    const formatterCases = countPattern(
      new RegExp(`case\\s+['"]${escaped}['"]`, 'g'),
      sourceFiles.filter((file) => file.endsWith('/channels/feishu/formatter.ts')),
    );
    const notes = [];
    if (producers.length === 0) notes.push('no producer');
    if (formatterCases.length === 0) notes.push('no formatter case');
    rows.push([
      type,
      producers.map((h) => `${h.file} (${h.count})`).join('<br>') || '-',
      formatterCases.map((h) => `${h.file} (${h.count})`).join('<br>') || '-',
      notes.join('; ') || '-',
    ]);
  }

  writeReport(
    'formattable-messages.md',
    `# Formattable Message Audit

Generated by \`npm run audit:debt\`.

${mdTable(['Message', 'Producers', 'Formatter cases', 'Notes'], rows)}`,
  );

  return rows.filter((row) => row[3] !== '-').length;
}

function commandNames() {
  const commandFiles = sourceFiles.filter((file) => file.includes('/engine/commands/'));
  const names = new Set();
  for (const file of commandFiles) {
    const text = fileText.get(file) ?? '';
    for (const match of text.matchAll(/readonly\s+name\s*=\s*['"]([^'"]+)['"]/g)) {
      names.add(match[1]);
    }
  }
  return [...names].sort();
}

function registeredCommandClasses() {
  const path = join(SRC, 'engine', 'commands', 'index.ts');
  const text = readFileSync(path, 'utf-8');
  return [...text.matchAll(/register\(new\s+([A-Za-z0-9_]+)\(/g)].map((match) => match[1]);
}

function publicSlashCommands() {
  const path = join(SRC, 'engine', 'commands', 'slash-policy.ts');
  const text = readFileSync(path, 'utf-8');
  const match = text.match(/new Set\((\[[\s\S]*?\])\)/);
  if (!match) return [];
  return [...match[1].matchAll(/['"]([^'"]+)['"]/g)].map((m) => m[1]).sort();
}

function actionNames() {
  const names = new Set();
  for (const file of sourceFiles) {
    const text = fileText.get(file) ?? '';
    for (const match of text.matchAll(/actionCallback\(\s*['"]([^'"]+)['"]/g)) {
      names.add(match[1]);
    }
    for (const match of text.matchAll(/action:\s*\{\s*kind:\s*['"]action['"],\s*name:\s*['"]([^'"]+)['"]/g)) {
      names.add(match[1]);
    }
  }
  return [...names].sort();
}

function auditCommandSurface() {
  const commands = commandNames();
  const commandSet = new Set(commands.map((cmd) => cmd.replace(/^\//, '')));
  const actions = actionNames();
  const publicCommands = publicSlashCommands();
  const actionRows = actions.map((action) => [
    action,
    commandSet.has(action) ? `/${action}` : '-',
    commandSet.has(action) ? '-' : 'action has no matching command',
  ]);
  const commandRows = commands.map((command) => [
    command,
    publicCommands.includes(command) ? 'yes' : 'internal/action only',
  ]);

  writeReport(
    'command-surface.md',
    `# Command and Action Surface Audit

Generated by \`npm run audit:debt\`.

Registered command classes: ${registeredCommandClasses().join(', ') || '-'}

Public text slash commands are the only slash commands intercepted from user text. Other registered commands should be reachable only from workbench/action callbacks or internal commands.

## Actions

${mdTable(['Action', 'Matching command', 'Notes'], actionRows)}

## Commands

${mdTable(['Command', 'Text visibility'], commandRows)}`,
  );

  return actionRows.filter((row) => row[2] !== '-').length;
}

function resolveImport(fromFile, specifier) {
  if (!specifier.startsWith('.')) return null;
  const base = resolve(dirname(fromFile), specifier);
  const candidates = [
    base,
    `${base}.ts`,
    base.replace(/\.js$/, '.ts'),
    join(base, 'index.ts'),
  ];
  return candidates.find((candidate) => fileText.has(normalize(candidate))) ?? null;
}

function auditTestOnlyImports() {
  const runtimeImports = new Map();
  const testImports = new Map();
  const importPattern = /(?:import|export)\s+(?:type\s+)?(?:[\s\S]*?\s+from\s+)?['"]([^'"]+)['"]/g;

  for (const file of files) {
    const text = fileText.get(file) ?? '';
    for (const match of text.matchAll(importPattern)) {
      const resolved = resolveImport(file, match[1]);
      if (!resolved || resolved.includes('/__tests__/')) continue;
      const bucket = file.includes('/__tests__/') ? testImports : runtimeImports;
      const list = bucket.get(resolved) ?? [];
      list.push(file);
      bucket.set(resolved, list);
    }
  }

  const rows = sourceFiles
    .filter((file) => testImports.has(file) && !runtimeImports.has(file))
    .filter((file) => !TEST_ONLY_IMPORT_ALLOWLIST.has(rel(file)))
    .map((file) => [
      rel(file),
      (testImports.get(file) ?? []).map(rel).join('<br>'),
      'directly imported only by tests',
    ]);

  writeReport(
    'test-only-imports.md',
    `# Test-only Direct Import Audit

Generated by \`npm run audit:debt\`.

This is a heuristic. Entry points and dynamically loaded modules may appear here if they are not directly imported by runtime TypeScript files.

${mdTable(['Source file', 'Test importers', 'Notes'], rows)}`,
  );

  return rows.length;
}

const summary = [
  ['canonical-events.md', auditCanonical()],
  ['formattable-messages.md', auditFormattableMessages()],
  ['command-surface.md', auditCommandSurface()],
  ['test-only-imports.md', auditTestOnlyImports()],
];

writeReport(
  'README.md',
  `# Debt Audit Reports

Generated by \`npm run audit:debt\`.

${mdTable(['Report', 'Candidate rows'], summary)}

These reports are candidate lists, not automatic deletion instructions. Treat rows as prompts for design review:

- no producer: likely dead schema branch
- no consumer: likely unused event/message
- tests-only: check whether tests are preserving obsolete behavior
- action has no matching command: callback may be stale or missing handler
`,
);

console.log(`Debt audit written to ${relative(ROOT, OUT_DIR)}`);
for (const [name, count] of summary) {
  console.log(`- ${name}: ${count} candidate row(s)`);
}
